//
//  SoccerFolding_1000000.hpp
//  Generated by SoccerFoldingTool
//
// Trials per roll: 1000000. Run seed: 15111071204579142915. Overall score: 84.66/100.
// Compile this header with only its matching generated .cpp file.
//

#ifndef SoccerFolding_1000000_hpp
#define SoccerFolding_1000000_hpp

#include <cstdint>

class SoccerFolding {
public:
    static void Collapse_Stage3_Outer_16(const std::uint8_t *pSourceA,
                                         const std::uint8_t *pSourceB,
                                         const std::uint8_t *pSourceC,
                                         const std::uint8_t *pSourceD,
                                         const std::uint8_t *pSourceE,
                                         const std::uint8_t *pSourceF,
                                         const std::uint8_t *pSourceG,
                                         const std::uint8_t *pSourceH,
                                         const std::uint8_t *pSourceI,
                                         const std::uint8_t *pSourceJ,
                                         const std::uint8_t *pSourceK,
                                         const std::uint8_t *pSourceL,
                                         const std::uint8_t *pSourceM,
                                         const std::uint8_t *pSourceN,
                                         const std::uint8_t *pSourceO,
                                         const std::uint8_t *pSourceP,
                                         std::uint8_t *pDestinationA,
                                         std::uint8_t *pDestinationB,
                                         std::uint8_t *pDestinationC,
                                         std::uint8_t *pDestinationD);
    
    static void Collapse_Stage3_Outer_8(const std::uint8_t *pSourceA,
                                        const std::uint8_t *pSourceB,
                                        const std::uint8_t *pSourceC,
                                        const std::uint8_t *pSourceD,
                                        const std::uint8_t *pSourceE,
                                        const std::uint8_t *pSourceF,
                                        const std::uint8_t *pSourceG,
                                        const std::uint8_t *pSourceH,
                                        std::uint8_t *pDestinationA,
                                        std::uint8_t *pDestinationB,
                                        std::uint8_t *pDestinationC,
                                        std::uint8_t *pDestinationD);
    
    static void Collapse_Stage2_4(const std::uint8_t *pSourceA,
                                  const std::uint8_t *pSourceB,
                                  const std::uint8_t *pSourceC,
                                  const std::uint8_t *pSourceD,
                                  std::uint8_t *pDestinationA,
                                  std::uint8_t *pDestinationB,
                                  std::uint8_t *pDestinationC,
                                  std::uint8_t *pDestinationD);
    
    static void Collapse_Stage1_4(const std::uint8_t *pSourceA,
                                  const std::uint8_t *pSourceB,
                                  const std::uint8_t *pSourceC,
                                  const std::uint8_t *pSourceD,
                                  std::uint8_t *pDestinationA,
                                  std::uint8_t *pDestinationB,
                                  std::uint8_t *pDestinationC,
                                  std::uint8_t *pDestinationD);
    
    static void Collapse_Stage0_4(const std::uint8_t *pSourceA,
                                  const std::uint8_t *pSourceB,
                                  const std::uint8_t *pSourceC,
                                  const std::uint8_t *pSourceD,
                                  std::uint8_t *pDestinationA,
                                  std::uint8_t *pDestinationB,
                                  std::uint8_t *pDestinationC,
                                  std::uint8_t *pDestinationD);
};

#endif /* SoccerFolding_1000000_hpp */
